language: python
python:
  - 2.7
before_install:
  - sudo apt-get -qq install nginx
  # This has to be done to let it create some files that nginx insists must exist, yet only root can create.
  - sudo /etc/init.d/nginx start
  - pip install coverage nose-cov lxml
  # don't bother compiling Cython itself, we're only going to use it once
  - pip install --install-option="--no-cython-compile" Cython
install:
  - python setup.py sdist
  - mkdir empty
  - cd empty
  - pip install ../dist/*
  # The following is supposed to help get rid of weird paths in the coverage output. I don't think it works.
  - INSTALLDIR=$(python -c "import os; import zss; print(os.path.dirname(zss.__file__))")
  - cp ../.coveragerc ./travis-coveragerc
  - echo >> ./travis-coveragerc
  - echo '[paths]' >> ./travis-coveragerc
  - echo "source =" >> ./travis-coveragerc
  - echo "    $INSTALLDIR" >> ./travis-coveragerc
  - cat ./travis-coveragerc
script:
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - nosetests --all-modules --with-cov --cov-conf ./travis-coveragerc --cov-report term-missing --cov ${INSTALLDIR} zss
after_success:
  - pip install coveralls && coveralls
notifications:
  email:
  - njs@pobox.com
