language: python
python:
  - 2.7
before_install:
  - sudo apt-get -qq install nginx
  - pip install --use-mirrors coverage nose-cov
install:
  - python setup.py sdist
  - pip install dist/*
script:
  - INSTALLDIR=$(python -c "import os; import zss; print(os.path.dirname(zss.__file__))")
  - mkdir empty
  - cd empty
  # The --exe is because python sometimes marks all installed modules
  # as executable, so without --exe nosetests will just ignore
  # everything. Baffling, but so it goes.
  - nosetests --all-modules --with-cov --cov-conf ../.coveragerc --cov-report term-missing zss
after_success:
  - pip install --use-mirrors coveralls && coveralls
notifications:
  email:
  - njs@pobox.com
