language: python
python:
  - 2.7
  - 3.3
  # this should work -- re-enable once travis has 3.4 installed!
  # - 3.4
before_install:
  - sudo apt-get -qq install nginx liblzma-dev
  # This has to be done to let it create some files that nginx insists must exist, yet only root can create.
  - sudo /etc/init.d/nginx start
  - pip install coverage nose-cov lxml
  - python -c 'import lzma' || pip install backports.lzma
  # don't bother compiling Cython itself, we're only going to use it once
  - pip install --install-option="--no-cython-compile" Cython
install:
  - python setup.py sdist
  - mkdir empty
  - cd empty
  - pip install ../dist/*
  - INSTALLDIR=$(python -c "import os; import zs; print(os.path.dirname(zs.__file__))")
script:
  # tell the tests that missing the 'zs' script is a hard-error
  - export ZS_REQUIRE_SCRIPT_TEST=1
  - nosetests --all-modules --with-cov --cov-conf ../.coveragerc --cov-report term-missing --cov ${INSTALLDIR} zs
after_success:
  - pip install coveralls && coveralls --rcfile=../.coveragerc
notifications:
  email:
  - njs@pobox.com
